# Generated by Django 4.2 on 2025-08-06 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor1', models.FloatField()),
                ('sensor2', models.FloatField()),
                ('sensor3', models.FloatField()),
                ('sensor4', models.FloatField()),
                ('sensor5', models.FloatField()),
                ('sensor6', models.FloatField()),
                ('sensor7', models.FloatField()),
                ('sensor8', models.FloatField()),
                ('sensor9', models.FloatField()),
                ('sensor10', models.FloatField()),
                ('sensor11', models.FloatField()),
                ('sensor12', models.FloatField()),
                ('sensor13', models.FloatField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
