# Generated by Django 5.2 on 2025-09-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('autorizado', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cartaorfid')),
            ],
        ),
    ]
