# Generated by Django 5.2 on 2025-11-03 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartaorfid_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriseSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ds18b20_1', models.FloatField(blank=True, null=True)),
                ('ds18b20_2', models.FloatField(blank=True, null=True)),
                ('ds18b20_3', models.FloatField(blank=True, null=True)),
                ('ds18b20_4', models.FloatField(blank=True, null=True)),
                ('ds18b20_5', models.FloatField(blank=True, null=True)),
                ('ds18b20_6', models.FloatField(blank=True, null=True)),
                ('dht11_1_temp', models.FloatField(blank=True, null=True)),
                ('dht11_1_hum', models.FloatField(blank=True, null=True)),
                ('dht11_2_temp', models.FloatField(blank=True, null=True)),
                ('dht11_2_hum', models.FloatField(blank=True, null=True)),
                ('uv_1', models.FloatField(blank=True, null=True)),
                ('uv_2', models.FloatField(blank=True, null=True)),
                ('wind_1', models.FloatField(blank=True, null=True)),
                ('wind_2', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PavimentosSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_a', models.FloatField(blank=True, null=True)),
                ('sensor_b', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor14',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
