# Generated by Django 5.2.4 on 2026-10-09 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_brisesensorreading_pavimentossensorreading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaorfid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartaorfid',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='cartaorfid',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='cartaorfid',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cartaorfid',
            name='nome_pessoa',
        ),
        migrations.AddField(
            model_name='cartaorfid',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cartaorfid',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono do Cartão'),
        ),
        migrations.AlterField(
            model_name='cartaorfid',
            name='uid',
            field=models.CharField(max_length=50, unique=True, verbose_name='UID do Cartão'),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Batida')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cartaorfid')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
